### ISSUE TITLE
Having problem on bower install hash.route

### ISSUE THREAD

**Issue by cention-mujibur-rahman** [MiguelCastillo/hash.route.js#4]
Hi, having the following problem to install it from bower. Is it possible to take a look?
bower.json:
`{
    "name": "hash.route",
    "dependencies": {
        "hash.route": "*"
    },
    "devDependencies": {
        "tmp": "~0.0.23"
    }   
}`

$ bower update
bower hash.route#\*          not-cached https://github.com/MiguelCastillo/hash.route.js.git#*
bower hash.route#\*             resolve https://github.com/MiguelCastillo/hash.route.js.git#*
bower tmp#~0.0.23           not-cached https://github.com/djdaniels90/tmp.git#~0.0.23
bower tmp#~0.0.23              resolve https://github.com/djdaniels90/tmp.git#~0.0.23
bower hash.route#\*            checkout master
Username for 'https://github.com': bower hash.route#\*               error Arguments to path.join must be strings

Stack trace:
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:488:13)
    at GitHubResolver.GitResolver._cleanup (/usr/local/lib/node_modules/bower/lib/core/resolvers/GitResolver.js:182:26)
    at /usr/local/lib/node_modules/bower/lib/core/resolvers/GitResolver.js:74:25
    at Promise.apply (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1122:26)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:752:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:1337:14
    at flush (/usr/local/lib/node_modules/bower/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)

Console trace:
Trace
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:74:17)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:109:18)
    at Logger.emit (events.js:107:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/update.js:25:16
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:808:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:834:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1079:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:752:41)

**Comment by cention-mujibur-rahman** [comment]
It was working before but today I found is not working.

**Comment by MiguelCastillo** [comment]
@cention-mujibur-rahman Hi - the issue seems like a bower dependency is having some issues.  A quick google search revealed this https://github.com/bower/bower/issues/1404.

I am going to close this issue, but if you find anything else related to hash.route, please let me know!

**Comment by cention-mujibur-rahman** [comment]
Hi Miguel,
Thanks for you response. I already checked the page you refereed.
Ok I will try to get whats wrong.
No problem found yet on hash.route, its working great!
Thanks

**Comment by cention-mujibur-rahman** [comment]
Well, Its more about bower version problem. 
Node: v0.12.4
Npm: 2.10.1
Bower: 1.2.6
That was failing to install hash.route and others packages as well.
Now I upgraded bower from 1.2.6 to 1.7.9 then it resolved the problem.

**Comment by MiguelCastillo** [comment]
Wonderful. I thought it would bower related.
